public class QuizLeaderboard {
    
    public static void runTask() {
        
        String regNo = 'YOUR_REG_NO';
        
        System.debug('Quiz Leaderboard Assignment - Salesforce');
        
        // Logic explanation:
        // 1. Call API 10 times
        // 2. Remove duplicates using (roundId + participant)
        // 3. Store scores in Map
        // 4. Generate leaderboard
        
    }
}